<nav class="navbar navbar-dark bg-dark" style = "margin-bottom: 30px">
    <div class = "container">
        <a class = "navbar-brand" href="../php/index.php">Taxonomia</a>

        <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarsExample01" aria-controls = "navbarsExample01" aria-expanded = "false" aria-label = "Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
        </button>

        <div class = "collapse navbar-collapse" id = "navbarsExample01">
            <ul class = "navbar-nav mr-auto">
                <li class = "nav-item dropdown">
                    <a class = "nav-link dropdown-toggle" href = "#" id = "dropdown01" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded = "false">Cadastrar</a>
                    <div class = "dropdown-menu" aria-labelledby = "dropdown01">
                        <a class = "dropdown-item" href="../php/formFamilia.php">Família</a>
                        <a class = "dropdown-item" href="../php/formGenero.php">Genêro</a>
                        <a class = "dropdown-item" href="../php/formEspecie.php">Espécie</a>
                    </div>
                </li>

                <li class = "nav-item dropdown">
                    <a class = "nav-link dropdown-toggle" href = "#" id = "dropdown02" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded = "false">Visualizar</a>
                    <div class = "dropdown-menu" aria-labelledby = "dropdown02">
                        <a class = "dropdown-item" href="../php/familia.php">Família</a>
                        <a class = "dropdown-item" href="../php/genero.php">Genêro</a>
                        <a class = "dropdown-item" href="../php/especie.php">Espécie</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
